before:
  hooks:
    - go mod download
builds:
  - env:
    goos:
      - linux
      - darwin
    goarch:
      - mips
      - amd64
    gomips:
      - softfloat
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
